### ISSUE TITLE
DukeMTMC

### ISSUE THREAD

**Issue by RitaDel** [FlyingRoastDuck/ACT_AAAI20#3]
I followed instructions in the readme, and duke is in data/dukemtmc/raw/. The dataset contains bounding_box_test, bounding_box_train and query.
An error occurs "Dataset not found or corrupted".
I tried to download Duke by using the URL, but it doesn't work.

**Comment by FlyingRoastDuck** [comment]
Hi, the data structure of dukemtmc is as follows:
![image](https://user-images.githubusercontent.com/29745430/101844629-d7147d00-3b87-11eb-9281-e533f9f6d5a6.png)
The simplest way to run our code is downloading "DukeMTMC-reID.zip" and put it under the "data/raw/". Duke dataset is currently not available due to privacy issues. If you want to reproduce the results, I can offer you the data but it is only for academic use. 
Send an email to me.

**Comment by RitaDel** [comment]
Now it works. Thank you
